name: f123dashboard
region: eu-central-1
yamlVersion: 2
services:
  email: true
frontend:
    path: ./client
    publish: dist/browser
    scripts:
        build: npm run build
        deploy:
            - npm install
            - npm update
        start:
            - npm start
    sdk:
        language: ts
        runtime: nodejs22.x
    subdomain: f123dashboard
backend:
  path: ./server
  language:
    name: js
    runtime: nodejs22.x
  scripts:
    deploy:
      - npm install
      - npm update
    local:
      - npm install
    start:
      - npm install
  cloudProvider: genezio